const DEFAULT_SIZE = 80;
const MIN_SIZE = 1;
const MAX_SIZE = 1024;
const SVG_SIZE = 32;
const ICON_SIZE = 24;

const COLORS = [
	"#F44336",
	"#f46236",
	"#f49236",
	"#c29e29",
	"#24b537",
	"#E91E63",
	"#9C27B0",
	"#673AB7",
	"#3F51B5",
	"#2196F3",
	"#03A9F4",
	"#00BCD4",
	"#009688",
	"#4CAF50",
	"#8BC34A",
	"#CDDC39",
	"#FFEB3B",
	"#FFC107",
	"#FF9800",
	"#FF5722",
];

const ICONS = [
	"ac_unit",
	"adjust",
	"airplanemode_active",
	"attach_file",
	"audiotrack",
	"beach_access",
	"brightness_3",
	"brightness_5",
	"brush",
	"bubble_chart",
	"bug_report",
	"business_center",
	"business",
	"category",
	"child_friendly",
	"directions_bike",
	"directions_boat",
	"directions_bus",
	"directions_car",
	"fastfood",
	"favorite",
	"filter_hdr",
	"filter_vintage",
	"fitness_center",
	"flag",
	"flash_on",
	"highlight",
	"local_dining",
	"local_florist",
	"local_movies",
	"local_pizza",
	"local_shipping",
	"local_taxi",
	"looks",
	"motorcycle",
	"pets",
	"star",
	"toys",
	"traffic",
	"vpn_key",
	"waves",
	"weekend",
];

module.exports = {
	DEFAULT_SIZE,
	MIN_SIZE,
	MAX_SIZE,
	SVG_SIZE,
	ICON_SIZE,
	COLORS,
	ICONS,
};
